const mockSearch = [
  {
    alunos: [1, 2, 3, 4, 5],
    recorrencia: 1,
    periodo: 'manha',
    skills: [
      'l1',
      'l2',
      'l3',
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
    ],
    // data : ['2021-02-']
    dia: ['segunda'],
    horario: ['10:00'],
  },
  {
    alunos: [1, 2, 3, 5],
    recorrencia: 1,
    periodo: 'manha',
    skills: [
      'l1',
      'l2',
      'l3',
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
    ],
    // data : ['2021-02-']
    dia: ['segunda'],
    horario: ['10:00'],
  },
  {
    alunos: [1, 2, 3, 4, 5, 6, 7],
    recorrencia: 2,
    periodo: 'tarde',
    skills: [
      'l1',
      'l2',
      'l3',
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
    ],
    // data : ['2021-02-']
    dia: ['terca', 'quarta'],
    horario: ['10:00', '09:00'],
  },
  {
    alunos: [1, 2, 3, 4, 5, 6, 7, 9, 12],
    recorrencia: 2,
    periodo: 'tarde',
    skills: [
      'l1',
      'l2',
      'l3',
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
    ],
    // data : ['2021-02-']
    dia: ['terca', 'quarta'],
    horario: ['10:00', '09:00'],
  },
];

export default mockSearch;
