import * as Contracts from './contracts';
import { mockListClassRooms } from './helpers/class-rooms';
import { bo } from './bo';

function main(
  recurrence: Contracts.Recurrence,
  period: Contracts.Period,
  day: Contracts.ScheduleDays,
  classrooms: Contracts.Classroom[],
): Contracts.ScheduleReturn[] {
  return bo({
    recurrence,
    period,
    day,
    classrooms,
  });
}

const mock = [
  {
    id: 1,
    students: [1, 2, 3, 4, 5, 6, 7, 8],
    recurrence: 1,
    period: 'manha',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['sexta'],
    hour: ['07:00'],
  },
  {
    id: 2,
    students: [1, 2, 3, 4, 5, 6],
    recurrence: 1,
    period: 'manha',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['sexta'],
    hour: ['08:00'],
  },
  {
    id: 3,
    students: [1, 2, 3, 4, 5, 6],
    recurrence: 1,
    period: 'tarde',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['sabado'],
    hour: ['10:00'],
  },
  {
    id: 4,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'manha',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['segunda', 'quarta'],
    hour: ['10:00', '08:00'],
  },
  {
    id: 5,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'manha',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['segunda', 'quarta'],
    hour: ['09:00', '07:00'],
  },
  {
    id: 6,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'tarde',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['segunda', 'quarta'],
    hour: ['15:00', '17:00'],
  },
  {
    id: 7,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'tarde',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['terca', 'quinta'],
    hour: ['15:00', '17:00'],
  },
  {
    id: 8,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'noite',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['terca', 'quinta'],
    hour: ['21:00', '20:00'],
  },
  {
    id: 9,
    students: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    recurrence: 2,
    period: 'manha',
    skills: [
      's1',
      's2',
      's3',
      'r1',
      'r2',
      'r3',
      'w1',
      'w2',
      'w3',
      'l1',
      'l2',
      'l3',
    ],
    day: ['terca', 'quinta'],
    hour: ['07:30', '08:30'],
  },
] as any;

// const classrooms = mockListClassRooms({
//   numberClassroom: 20,
// });

// main(1, 'manha', ['segunda', 'quarta'], classrooms);

export { mockListClassRooms, main, mock };
